Name : Amardeep Kumar

Roll No : DA25M502

# **Question 1:** Logistic Regression from Scratch for Spam Classification

---

The objective is to build a binary spam classifier using Logistic Regression implemented from scratch using only NumPy. The use of sklearn’s LogisticRegression or similar
high-level machine learning libraries is not permitted.

The model must be trained and evaluated on the Enron Spam dataset (https://huggingface.co/datasets/bvk/ENRON-spam) and tested on a different dataset, the SMS Spam dataset(https://huggingface.co/datasets/bvk/SMS-spam).

Report the following performance metrics for both training and testing splits:
- Confusion Matrix
- Accuracy
- Precision
- Recall
- F1-Score

Compare the model’s performance on the two datasets and provide possible reasons for any observed differences in  the results.

In [ ]:
#import necessary libraries
from google.colab import data_table
data_table.enable_dataframe_formatter()

# from google.colab import data_table
# data_table.disable_dataframe_formatter()

# huggingface library to load the dataset
from datasets import load_dataset

import pandas as pd
import numpy as np

## Load Dataset

In [ ]:
# Load the Enron Spam dataset
enron_dataset = load_dataset('bvk/ENRON-spam')
#load the SMS Spam Dataset
sms_dataset = load_dataset('bvk/SMS-spam')

# Display information about the dataset
print(enron_dataset)
print(sms_dataset)

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.
Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

DatasetDict({
    train: Dataset({
        features: ['label', 'email', 'filename'],
        num_rows: 33716
    })
})
DatasetDict({
    train: Dataset({
        features: ['label', 'data'],
        num_rows: 5574
    })
})

In [ ]:
#convert eron and sms dataset to pandas dataset
if 'train' in enron_dataset:
    eron_train_df = enron_dataset['train'].to_pandas()

if 'train' in sms_dataset:
    sms_test_df = sms_dataset['train'].to_pandas()

In [ ]:
print("\nFirst 5 rows of the eron dataset:")
display(eron_train_df.head())

First 5 rows of the eron dataset:

,label,email,filename
0,0,['Subject: christmas tree farm pictures \n'],0001.1999-12-10.farmer.ham.txt
1,0,['Subject: re : rankings \nthank you .'],0001.1999-12-10.kaminski.ham.txt
2,0,['Subject: leadership development pilot \nsal...,0001.2000-01-17.beck.ham.txt
3,0,"[""Subject: key dates and impact of upcoming sa...",0001.2000-06-06.lokay.ham.txt
4,0,['Subject: key hr issues going forward \na ) ...,0001.2001-02-07.kitchen.ham.txt

In [ ]:
print("\nFirst 5 rows of the sms dataset:")
display(sms_test_df.head())

First 5 rows of the sms dataset:

   label                                               data
0      1  ["Free entry in 2 a wkly comp to win FA Cup fi...
1      1  ['"FreeMsg Hey there darling it\'s been 3 week...
2      1  ['WINNER!! As a valued network customer you ha...
3      1  ['Had your mobile 11 months or more? U R entit...
4      1  ['"SIX chances to win CASH! From 100 to 20,000...

In [ ]:
#basic summary
print("\nSummary of the eron dataset:")
print("="*50)
eron_train_df.info()
print("\nSummary of the sms dataset:")
print("="*50)
sms_test_df.info()

Summary of the eron dataset:
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33716 entries, 0 to 33715
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   label     33716 non-null  int64
 1   email     33716 non-null  object
 2   filename  33716 non-null  object
dtypes: int64(1), object(2)
memory usage: 790.3+ KB

Summary of the sms dataset:
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5574 entries, 0 to 5573
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   5574 non-null   int64
 1   data    5574 non-null   object
dtypes: int64(1), object(1)
memory usage: 87.2+ KB

In [ ]:
X_train = eron_train_df['email']
y_train = eron_train_df['label']
X_test = sms_test_df['data']
y_test = sms_test_df['label']

## Vectorization

In [ ]:
def vectorization(raw_dataset):
    from sklearn.feature_extraction.text import CountVectorizer
    vectorizer = CountVectorizer(stop_words="english",min_df = 5 , max_features = 1612) #1612 feature becuase getting max feature 1612 in test
    numerical_dataset = vectorizer.fit_transform(raw_dataset)
    return numerical_dataset,vectorizer

In [ ]:
# for train datset
X_train_vector,vectorizer = vectorization(X_train)
# print(X_train_vector.toarray())
# print(vectorizer.get_feature_names_out())
X_train_transformed = pd.DataFrame(X_train_vector.toarray(),columns=vectorizer.get_feature_names_out())
print("\n Transformed Train Dataset :")
print("="*50)
X_train_transformed.head()

 Transformed Train Dataset :
==================================================
Warning: Total number of columns (1612) exceeds max_columns (20). Falling back to pandas display.

,00,000,0000,01,02,03,04,05,06,07,...,x01,xls,xp,yahoo,year,years,yes,yesterday,york,young
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0

In [ ]:
# for test datset
X_test_vector,vectorizer = vectorization(X_test)
# print(X_test_vector.toarray())
# print(vectorizer.get_feature_names_out())
X_test_transformed = pd.DataFrame(X_test_vector.toarray(),columns=vectorizer.get_feature_names_out())
print("\n Transformed Test Dataset :")
print("="*50)
X_test_transformed.head()

 Transformed Test Dataset :
==================================================
Warning: Total number of columns (1612) exceeds max_columns (20). Falling back to pandas display.

,00,000,02,03,04,06,0800,08000839402,08000930705,0870,...,yo,yoga,yogasana,yr,yrs,yun,yup,zed,ã¼,ãœ
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Logistic Regression (Using Numpy from Scratch)
**`Logistic Regression Equation:`**

The predicted probability is given by the sigmoid function applied to a linear combination of features:

$$\hat{y} = \sigma(Xw + b)$$
**`Sigmoid Function:`**

The sigmoid function maps any real-valued number to a value between 0 and 1:

$$\sigma(z) = \frac{1}{1 + e^{-z}}$$

**`Loss (Binary Cross-Entropy):`**

The Binary Cross-Entropy loss function $L$ for a single sample is:

$$L = -\frac{1}{N} \sum (y \log \hat{y} + (1 - y) \log (1 - \hat{y}))$$

Where:
- $N$ is the number of samples.
- $y$ is the true label (0 or 1).
- $\hat{y}$ is the predicted probability.

**`Gradients:`**

To update the weights $w$ and bias $b$ during gradient descent, we calculate the partial derivatives of the loss function with respect to $w$ and $b$:

**`Gradient of Loss with respect to Weights (dw):`**

$$\frac{\partial L}{\partial w} = \frac{1}{N} X^T (\hat{y} - y)$$

**`Gradient of Loss with respect to Bias (db):`**

$$\frac{\partial L}{\partial b} = \frac{1}{N} \sum (\hat{y} - y)$$

### Defining : Sigmoid + fit + Gradient

In [ ]:
class LogisticRegression:
    def __init__(self, learning_rate=0.01, num_iterations=100):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations

    #sigmoid method
    def sigmoid(self,z):
        y_predicted_probability = np.round(1/(1+np.exp(-z)),decimals=3)
        return y_predicted_probability

    #training module
    def fit(self,X,y):
        n_samples, n_features = X.shape
        self.w = np.zeros(n_features)
        self.b = 0
        y = np.array(y)
        for _ in range(self.num_iterations):
            #pridcting the probability forward pass
            z = np.dot(X,self.w) + self.b
            y_predicted_probability = self.sigmoid(z)

            #calculating graident and this is batch gradient descent
            dw = (1/n_samples)*np.dot(X.T,(y_predicted_probability -y))
            db = (1/n_samples)*np.sum((y_predicted_probability -y))
            #updating gradient
            self.w = self.w - self.learning_rate * dw
            self.b = self.b - self.learning_rate * db

    #prediction module
    def predict(self,X):
        z = np.dot(X,self.w) + self.b
        y_predicted_probability = self.sigmoid(z)
        return (y_predicted_probability >= 0.5).astype(int)

### Train And  Evaluate

In [ ]:
# Train And  Evaluate
logistic_regression_model = LogisticRegression(learning_rate=0.01, num_iterations=1000)
logistic_regression_model.fit(X_train_transformed, y_train)

In [ ]:
train_preds = logistic_regression_model.predict(X_train_transformed)

In [ ]:
test_preds = logistic_regression_model.predict(X_test_transformed)

### Confusion Matrix + Accuracy + Precision + Recall + F1-Score

In [ ]:
#calculating confusion matrix module
def confusion_matrix(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    return TP, TN, FP, FN
# Accuracy + Precision + Recall + F1-Score module
def metrics(y_true, y_pred):
    TP, TN, FP, FN = confusion_matrix(y_true, y_pred)
    accuracy = (TP + TN) / (TP + TN + FP + FN)
    precision = TP / (TP + FP + 1e-9)
    recall = TP / (TP + FN + 1e-9)
    f1 = 2 * precision * recall / (precision + recall + 1e-9)
    return accuracy, precision, recall, f1

In [ ]:
train_metrics = metrics(np.array(y_train), train_preds)
test_metrics = metrics(np.array(y_test), test_preds)
print("Training Metrics (Enron)")
print("="*50)
print("Accuracy %:", train_metrics[0]*100)
print("Precision :", train_metrics[1])
print("Recall :", train_metrics[2])
print("F1-Score :", train_metrics[3])
print("\nTesting Metrics (SMS)")
print("="*50)
print("Accuracy %:", test_metrics[0]*100)
print("Precision:", test_metrics[1])
print("Recall:", test_metrics[2])
print("F1-Score:", test_metrics[3])

Training Metrics (Enron)
==================================================
Accuracy %: 93.94056234428759
Precision : 0.8957308778905045
Recall : 0.9970881136799838
F1-Score : 0.9436957415435477

Testing Metrics (SMS)
==================================================
Accuracy %: 13.060638679583784
Precision: 0.11855574167129748
Recall: 0.8527443105744943
F1-Score: 0.2081699344261339

## Obserbations:
- Here Result on Test Dataset(SMS Spam) coming singficantly low, the reason i am assuming is that i have limit the max feature size to 1612 on training(Enron) dataset.
- In SMS dataset am getting max feature 1612 , keeping feature size more than in the model creating challenge will pridction as the dataset coming from two different type of SPAMS , the Enron dataset target mail spam which content size is more than the SMS Spam dataset.